### PR TITLE
Add PHPDoc to Cloudinary\Api and Exceptions

### PR DESCRIPTION
**Pull request by const-cloudinary**

### CODE REVIEW

**Comment by holtkamp** [comment]
Just wondering: what is the added value of this? In general there is a movement towards "less" useless PHPDoc...

**Comment by const-cloudinary** [comment]
The idea is to provide an overview of the APIs, provide direct links to the documentation pages and describe available options.

**Comment by holtkamp** [comment]
Well, the PHPDoc that is added by this Pull Request can all be derived from the code itself by modern IDE's and documentation tools. This only increases maintenance load and the chance of "getting out of sync" with the actual code. 

Just my 2 cents 😄

**Comment by holtkamp** [comment]
> Type hinting is a really great feature of PHP7, unfortunately 85% of the web sites are still using PHP5. We can't stop supporting them.

Ok, that makes sense. 

However THIS pull request does not add any type hinting. Only class names and "@package" information (which is the same as the namespace) 🤓

**Comment by const-cloudinary** [comment]
Oh, yes, I'll add some description to the exception classes.
But, the main part of the PR is this file:
https://github.com/cloudinary/cloudinary_php/pull/115/files#diff-0adfbcc2ab7bc20ad7694203ce94ccfa

**Pull request merged**
