### PR TITLE
Fix unit tests on staging server

### PR DESCRIPTION
**Pull request by const-cloudinary**
Fix namespace in SearchTest
Add Assertions

### CODE REVIEW

**Comment by cloudinary-misha** [comment]
@const-cloudinary, please add branch except statement to .travis.yml
to avoid double build on staging-test branch.

You can see example on pycloudinary/feature/ignore-staging-in-ci
https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches

**Comment by const-cloudinary** [comment]
@cloudinary-misha, this and pycloudinary/feature/ignore-staging-in-ci branches will be merged to master, no need to do it explicitly here

**Comment by const-cloudinary** [comment]
@cloudinary-misha, please verify

**Comment by cloudinary-misha** [comment]
Branch works properly against staging

**Pull request merged**
