### PR TITLE
Added access_mode parameter to build_upload_params

### PR DESCRIPTION
**Pull request by brian-cloudinary**

### CODE REVIEW

**Comment by const-cloudinary** [comment]
This functionality is deprecated in favour of access_control

**Comment by slootjes** [comment]
@const-cloudinary why is this not mentioned in the documentation then?

https://cloudinary.com/documentation/image_upload_api_reference#optional_parameters
https://cloudinary.com/documentation/admin_api#update_access_mode

**Comment by shirlymanor** [comment]
@slootjes agree I've opened a request on your behalf to add a note in our documentation that update_access_mode is deprecated and we would recommend using access control.

**Comment by slootjes** [comment]
@shirlymanor thanks for your quick reply. Today I tried the access_control but it didn't work, it didn't matter what I tried but I could always use the public url to load the upload (without any token). Where can I obtain information on how to achieve certain things if the documentation is incorrect/incomplete?

**Pull request closed without merging**
