### PR TITLE
Detect data URLs with suffix in mime type

### PR DESCRIPTION
**Pull request by rioderelfte**
This allows uploading SVG images (mime type image/svg+xml).

### CODE REVIEW

**Comment by const-cloudinary** [comment]
@rioderelfte , thanks for the PR, would you mind updating the unit test `test_upload_non_local_file`?

**Comment by rioderelfte** [comment]
I added a new test case uploading an SVG file: 4a78b5ccc139e937046a1b6ac750176d43c3c5a8

**Comment by const-cloudinary** [comment]
@rioderelfte thank you for contribution!

**Comment by rioderelfte** [comment]
Thank you very much for the fast review 🎉

**Pull request merged**
